import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import React, { FC, useState } from "react";

export default function Home() {
  const [count, setCount] = useState(0)

  const add = (factor = 1) => {
    setCount(count + factor);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="hero min-h-full py-10">
          <div className="hero-content text-center">
              <div className="max-w-md">
                  <h1 className="text-5xl font-bold">REPTEX</h1>
                  <p className="py-6">NextJS + React + Tailwind + DaisyUI</p>
                  <button className="btn btn-primary" onClick={() => add()}>count is: { count }</button>
              </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
