export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function Page() {
  return (
    <div className="ds-hero min-h-full py-10">
      <div className="ds-hero-content text-center">
        <div className="max-w-md">
          <h1 className="text-5xl font-bold">REPTEX</h1>
          <p className="py-6">NextJS + React + Tailwind + DaisyUI</p>
        </div>
      </div>
    </div>
  );
}
