export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function Page() {
  return (
    <div className="ds-hero min-h-full py-10">
      <div className="ds-hero-content text-center">
        <div className="max-w-md">
          <h1 className="text-5xl font-bold">REPTEX</h1>
          <p className="py-6">NextJS + React + Tailwind + DaisyUI</p>
          <p>1</p>
          <p>2</p>
          <p>3</p>
          <p>4</p>
          <p>5</p>
          <p>6</p>
          <p>7</p>
          <p>8</p>
          <p>9</p>
          <p>10</p>
          <p>11</p>
          <p>12</p>
          <p>13</p>
          <p>14</p>
          <p>15</p>
          <p>16</p>
          <p>17</p>
          <p>18</p>
          <p>19</p>
          <p>20</p>
          <p>21</p>
          <p>22</p>
          <p>23</p>
          <p>24</p>
          <p>25</p>
        </div>
      </div>
    </div>
  );
}
